# Generated by Django 3.0.6 on 2020-06-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_auto_20200601_1557'),
    ]

    operations = [
    ]
