# Generated by Django 3.0.6 on 2020-06-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_auto_20200601_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetry',
            options={'ordering': ['time', 'device'], 'verbose_name_plural': 'Telemetry'},
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='id',
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
