# Generated by Django 3.0.6 on 2020-06-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_auto_20200602_2131'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT create_hypertable('telemetry_telemetry', 'time');"),
    ]
