# Generated by Django 3.0.6 on 2020-06-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetry',
            options={'ordering': ['time', 'device']},
        ),
    ]
