# Generated by Django 3.0.6 on 2020-06-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_auto_20200603_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='transport',
            field=models.CharField(choices=[('http', 'http'), ('mqtt', 'mqtt')], default='http', max_length=4),
        ),
    ]
