# -*- coding: utf-8 -*-
# vim: syntax=dockerfile tabstop=4 shiftwidth=4 softtabstop=4
#
# BITE - A Basic/IoT/Example
# Copyright (C) 2020-2021 Daniele Viganò <daniele@vigano.me>
#
# BITE is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BITE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM daniviga/ntpd

COPY ./chrony.keys /etc/chrony/chrony.keys

RUN echo "keyfile /etc/chrony/chrony.keys" \
        >> /etc/chrony/chrony.conf 

EXPOSE 123/udp
ENTRYPOINT ["chronyd", "-d", "-s", "-x"]
