language: python
dist: bionic

services:
 - docker

before_install:
  - pip -q install -U docker-compose -r requirements.txt

jobs:
  include:
  - stage: build
    # before_script:
    #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    script:
      - docker-compose -f docker/docker-compose.yml build
    #  - docker push daniviga/beer
    #  - docker push daniviga/ntpd
  - stage: django
    install:
      - docker-compose -f docker/docker-compose.yml build
    #  - docker-compose -f docker/docker-compose.yml pull
    before_script:
      - docker-compose -f docker/docker-compose.yml up -d
    script:
      - docker-compose -f docker/docker-compose.yml exec bite python manage.py test
  - stage: simulator
    env: 
      - IOT_TL=http
    install:
      - docker-compose -f docker/docker-compose.yml build
    #  - docker-compose -f docker/docker-compose.yml pull
    before_script:
      - docker-compose -f docker/docker-compose.yml up -d
    script:
      - ./docker/simulator/device_simulator.py -s 'http1234' -d 5 &
      - sleep 10
      - curl -sf http://localhost/telemetry/http1234/last/
  - stage: simulator
    env:
      - IOT_TL=mqtt
    install:
      - docker-compose -f docker/docker-compose.yml build
    #  - docker-compose -f docker/docker-compose.yml pull
    before_script:
      - docker-compose -f docker/docker-compose.yml up -d
    script:
      - ./docker/simulator/device_simulator.py -s 'mqtt1234' -d 5 &
      - sleep 10
      - curl -sf http://localhost/telemetry/mqtt1234/last/
