# Generated by Django 3.0.6 on 2020-06-02 21:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200601_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=128, unique=True, validators=[api.models.device_validation]),
        ),
    ]
