version: "3.7"

services:
  timescale:
    ports:
        - "5432:5432"

  broker:
    ports:
        - "${CUSTOM_DOCKER_IP:-0.0.0.0}:1883:1883"
        - "${CUSTOM_DOCKER_IP:-0.0.0.0}:9001:9001"

  bite:
    volumes:
      - ../bite:/srv/app/bite
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
        - "${CUSTOM_DOCKER_IP:-0.0.0.0}:8000:8000"

  data-migration:
    volumes:
      - ../bite:/srv/app/bite

  mqtt-to-db:
    volumes:
      - ../bite:/srv/app/bite
