# -*- coding: utf-8 -*-
# vim: tabstop=2 shiftwidth=2 softtabstop=2
#
# BITE - A Basic/IoT/Example
# Copyright (C) 2020-2021 Daniele Viganò <daniele@vigano.me>
#
# BITE is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BITE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "3.7"

services:
  timescale:
    ports:
        - "5432:5432"

  broker:
    ports:
        - "${CUSTOM_DOCKER_IP:-0.0.0.0}:18883:1883"
        - "${CUSTOM_DOCKER_IP:-0.0.0.0}:9001:9001"

  bite:
    volumes:
      - ../bite:/srv/app/bite
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
        - "${CUSTOM_DOCKER_IP:-0.0.0.0}:8000:8000"

  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
        - "${CUSTOM_DOCKER_IP:-0.0.0.0}:29092:29092"

  data-migration:
    volumes:
      - ../bite:/srv/app/bite

  static-files:
    volumes:
      - ../bite:/srv/app/bite

  dispatcher:
    volumes:
      - ../bite:/srv/app/bite

  handler:
    volumes:
      - ../bite:/srv/app/bite
