version: "3.7"

networks:
  net:

volumes:
  pgdata:

x-op-service-default: &service_default
  restart: unless-stopped
  init: true

services:
  ntpd:
    <<: *service_default
    image: daniviga/ntpd
    networks:
      - net
    ports:
      - "127.0.0.1:123:123/udp"

  timescale:
    <<: *service_default
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_USER: "freedcs"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - net
    ports:
      - "127.0.0.1:5432:5432"

  # mosquitto simple deployment
  # mqtt:
  #   <<: *service_default
  #   # image: vernemq/vernemq
  #   # environment:
  #   #   DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
  #   #   DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
  #   image: eclipse-mosquitto
  #   networks:
  #     - net
  #   ports:
  #     - "1883:1883"
  #     - "9001:9001"

  rabbitmq:
    <<: *service_default
    image: rabbitmq:3-management-alpine
    environment:
      # RABBITMQ_DEFAULT_VHOST: "freedcs"
      RABBITMQ_DEFAULT_USER: "freedcs"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - net
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"

  edge:
    <<: *service_default
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR:
    networks:
      - net
    ports:
      - "127.0.0.1:22375:2375"
