version: "3.7"

networks:
  net:

volumes:
  pgdata:

x-op-service-default: &service_default
  restart: unless-stopped
  init: true

services:
  timescale:
    <<: *service_default
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_USER: "timescale"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - net
    ports:
      - "127.0.0.1:5432:5432"
