version: "3.7"

services:
  timescale:
    ports:
        - "5432:5432"

  bite:
    volumes:
      - ../bite:/srv/app/bite
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
        - "8000:8000"

  data-migration:
    volumes:
      - ../bite:/srv/app/bite

  mqtt-to-db:
    volumes:
      - ../bite:/srv/app/bite
