# Generated by Django 3.0.6 on 2020-06-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['updated_time', 'serial']},
        ),
        migrations.AlterModelOptions(
            name='whitelist',
            options={'ordering': ['serial', 'updated_time']},
        ),
    ]
