# Generated by Django 3.2.7 on 2021-09-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_timescale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
