# Generated by Django 3.0.6 on 2020-06-03 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_auto_20200602_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='clock',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
