# Generated by Django 3.0.7 on 2020-06-19 16:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import telemetry.models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_telemetry_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[telemetry.models.telemetry_validation]),
        ),
    ]
