# Generated by Django 3.1 on 2020-08-23 13:40

from django.db import migrations, models
import telemetry.models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_auto_20200619_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='payload',
            field=models.JSONField(validators=[telemetry.models.telemetry_validation]),
        ),
    ]
