version: "3.7"

x-op-service-default: &service_default
  restart: always
  init: true
  tty: true

services:
  device-http:
    <<: *service_default
    build:
      context: ../simulator
    image: daniviga/bite-device-simulator
    environment:
      IOT_HTTP: "http://ingress"
      # IOT_SERIAL: "http1234"
      # IOT_DELAY: 10
      IOT_DEBUG: 1
    network_mode: "host"

  device-mqtt:
    <<: *service_default
    build:
      context: ../simulator
    image: daniviga/bite-device-simulator
    environment:
      IOT_HTTP: "http://ingress"
      IOT_MQTT: "broker:1883"
      # IOT_SERIAL: "mqtt1234"
      # IOT_DELAY: 10
      IOT_DEBUG: 1
    command: ["/opt/bite/device_simulator.py", "-t", "mqtt"]
    network_mode: "host"
